#!/usr/bin/env bash
# Generate brain/.env with cryptographically valid dev secrets.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/brain/.env"

if [[ -f "$ENV_FILE" ]] && grep -q "JWT_SECRET_KEY=penlo-dev" "$ENV_FILE" 2>/dev/null; then
  echo "brain/.env already configured for local dev"
  exit 0
fi

JWT_SECRET=$(openssl rand -hex 32)
WEBHOOK_SECRET=$(openssl rand -hex 16)
CRM_SECRET=$(openssl rand -hex 16)
SLACK_SECRET=$(openssl rand -hex 16)
FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
LANGFUSE_SECRET=$(openssl rand -hex 32)
MCP_TOKEN=$(openssl rand -hex 32)

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/generate-env.sh — safe for local dev only
POSTGRES_USER=penlo
POSTGRES_PASSWORD=penlo
POSTGRES_DB=penlo_enterprise

DATABASE_URL=postgresql+asyncpg://penlo:penlo@localhost:5432/penlo_enterprise

JWT_SECRET_KEY=penlo-dev-${JWT_SECRET}
JWT_ALGORITHM=HS256
JWT_EXPIRE_MINUTES=60
JWT_REFRESH_EXPIRE_DAYS=30

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-sk-ant-dev-placeholder}
CLAUDE_MODEL=claude-sonnet-4-6

LANGFUSE_HOST=http://localhost:3001
LANGFUSE_PUBLIC_KEY=pk-lf-dev
LANGFUSE_SECRET_KEY=sk-lf-${LANGFUSE_SECRET}
LANGFUSE_NEXTAUTH_URL=http://localhost:3001
LANGFUSE_NEXTAUTH_SECRET=${LANGFUSE_SECRET}
LANGFUSE_SALT=${LANGFUSE_SECRET}

PENLO_WEBHOOK_SECRET=${WEBHOOK_SECRET}
SLACK_SIGNING_SECRET=${SLACK_SECRET}
CRM_WEBHOOK_SECRET=${CRM_SECRET}

SLACK_CLIENT_ID=
SLACK_CLIENT_SECRET=
SLACK_TOKEN_ENCRYPTION_KEY=${FERNET_KEY}

PENLO_BASE_URL=http://localhost:8000
PENLO_FRONTEND_URL=http://localhost:5173
CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000

GOOGLE_CLIENT_ID=
ALLOW_COMPANY_SIGNUP=true

PENLO_MCP_TOKENS={}
PENLO_API_TOKEN=${MCP_TOKEN}
PENLO_API_COMPANY_ID=00000000-0000-4000-8000-000000000001

# Disable the 1.3GB HuggingFace model download in local dev.
# Semantic search gracefully falls back to label matching.
# Set to false in Docker or production to enable full vector search.
SKIP_EMBEDDINGS=true
EMBEDDING_MODEL=BAAI/bge-large-en-v1.5
EOF

echo "Generated $ENV_FILE"
echo "MCP token (for Cursor): $MCP_TOKEN"
